apiVersion: v1
kind: Namespace
metadata:
  name: sample-test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mycontroller
  namespace: sample-test
secrets:
- name: mycontroller-token
imagePullSecrets:
- name: mycontroller-secret
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mycontroller-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mycontroller-role-binding
subjects:
- kind: ServiceAccount
  name: mycontroller
  namespace: sample-test
roleRef:
  kind: ClusterRole
  name: mycontroller-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycontroller
  namespace: sample-test
spec:
  selector:
    matchLabels:
      app: mycontroller
  template:
    metadata:
      labels:
        app: mycontroller
    spec:
      serviceAccountName: mycontroller
      containers:
        - name: mycontroller
          image: mycontroller:v1
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: Always
