apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-not
  labels:
    app: nginx-not
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-not
  template:
    metadata:
      labels:
        app: nginx-not
    spec:
      containers:
      - name: nginx-not
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP